name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  NAMESPACE: demo0811
  AKS_CLUSTER: demo0811
  AKS_RESOURCE_GROUP: demo0811

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/demo0811:${{ github.sha }}

    # Deploy AKS

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure AKS Get Credentials
        run: |
            az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Replace IMAGE_TAG variable
        run: sed -i "s/$IMAGE_TAG/${{ github.sha }}/g" k8s/application.yaml

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/application.yaml -n ${{ env.NAMESPACE }}
